using Microsoft.Extensions.Logging;

namespace TinyLocalization.Options;

/// <summary>
/// Represents configuration options for distributed logs fusion cache, allowing customization of cache durations,
/// logging levels, fail-safe behavior, and distributed cache connectivity.
/// </summary>
/// <remarks>Use this class to configure the behavior and reliability of distributed caching operations, including
/// circuit breaker durations, error logging granularity, fail-safe thresholds, and Redis connection settings. Adjusting
/// these options can help optimize cache performance and resilience in distributed environments.</remarks>
public class DistributedLogsFusionCacheOptions
{
    /// <summary>
    /// Gets or sets the duration, in minutes, that the circuit breaker remains open after a failure is detected in the
    /// distributed cache.
    /// </summary>
    /// <remarks>This property determines how long requests to the distributed cache are blocked following a
    /// failure. Adjusting this value can help control the recovery period and manage system resilience in the event of
    /// cache outages.</remarks>
    public int DistributedCacheCircuitBreakerDurationInMinutes { get; set; } = 2;

    /// <summary>
    /// Gets or sets the log level used for recording fail-safe activation events.
    /// </summary>
    /// <remarks>The default value is LogLevel.Debug, which provides detailed logging for troubleshooting
    /// activation failures. Adjust this property to control the verbosity of logs related to fail-safe
    /// activations.</remarks>
    public LogLevel FailSafeActivationLogLevel { get; set; } = LogLevel.Debug;

    /// <summary>
    /// Gets or sets the log level used for reporting serialization errors.
    /// </summary>
    /// <remarks>Adjust this property to control the severity of log messages generated when serialization
    /// errors occur. Setting a lower log level increases verbosity, which can be useful for debugging or monitoring
    /// serialization issues.</remarks>
    public LogLevel SerializationErrorsLogLevel { get; set; } = LogLevel.Warning;

    /// <summary>
    /// Gets or sets the log level used for messages related to synthetic timeouts in the distributed cache.
    /// </summary>
    /// <remarks>Adjusting this property controls the verbosity of log output for synthetic timeout events,
    /// which can assist in diagnosing cache performance or reliability issues. Set to a higher log level to reduce log
    /// noise in production environments.</remarks>
    public LogLevel DistributedCacheSyntheticTimeoutsLogLevel { get; set; } = LogLevel.Debug;

    /// <summary>
    /// Gets or sets the log level used for logging errors related to the distributed cache.
    /// </summary>
    /// <remarks>This property allows configuration of the logging level for distributed cache errors,
    /// enabling developers to control the verbosity of log output for error conditions.</remarks>
    public LogLevel DistributedCacheErrorsLogLevel { get; set; } = LogLevel.Error;

    /// <summary>
    /// Gets or sets the log level used for synthetic timeout events generated by the factory.
    /// </summary>
    /// <remarks>This property controls the verbosity of log messages related to synthetic timeouts, which can
    /// assist in diagnosing operational issues. The default value is <see cref="LogLevel.Debug"/>, providing detailed
    /// logging output.</remarks>
    public LogLevel FactorySyntheticTimeoutsLogLevel { get; set; } = LogLevel.Debug;

    /// <summary>
    /// Gets or sets the log level used to record errors that occur during factory operations.
    /// </summary>
    /// <remarks>The default value is <see cref="LogLevel.Error"/>, which means only error-level messages are
    /// logged unless this property is changed. Adjust this property to control the verbosity of error logging for
    /// factory-related issues.</remarks>
    public LogLevel FactoryErrorsLogLevel { get; set; } = LogLevel.Error;

    /// <summary>
    /// Gets or sets the duration, in minutes, for which the cache remains valid before it expires.
    /// </summary>
    /// <remarks>The default value is 10 minutes. Adjust this value to optimize cache performance based on the
    /// application's requirements.</remarks>
    public int CacheDurationInMinutes { get; set; } = 10;

    /// <summary>
    /// Gets or sets a value indicating whether fail-safe mode is enabled.
    /// </summary>
    /// <remarks>When enabled, fail-safe mode prioritizes system stability and reliability over performance.
    /// This mode is typically used in scenarios where maintaining consistent operation is critical, even if it results
    /// in reduced throughput or responsiveness.</remarks>
    public bool FailSafeModeEnabled { get; set; } = true;

    /// <summary>
    /// Gets or sets the maximum duration, in minutes, that fail-safe operations are allowed to run.
    /// </summary>
    /// <remarks>Set this property to define an upper limit for the duration of fail-safe mechanisms. Adjust
    /// the value according to the application's requirements for responsiveness and reliability. Exceeding this
    /// duration may indicate an abnormal condition or require intervention.</remarks>
    public int FailSafeMaxDurationInMinutes { get; set; } = 120;

    /// <summary>
    /// Gets or sets the duration, in seconds, that the system waits before resuming normal operations after a fail-safe
    /// condition is triggered.
    /// </summary>
    /// <remarks>This property determines the length of the throttle period applied when a fail-safe event
    /// occurs. Adjust this value to control how long the system remains in a throttled state before attempting to
    /// return to normal operation. The default value is 30 seconds.</remarks>
    public int FailSafeThrottleDurationInSeconds { get; set; } = 30;

    /// <summary>
    /// Gets or sets the threshold, as a value between 0 and 1, that determines when to trigger an eager data refresh.
    /// </summary>
    /// <remarks>A higher value increases the likelihood that data will be refreshed eagerly, while a lower
    /// value reduces it. This property is typically used to control the proportion of data access or staleness that
    /// prompts a refresh operation.</remarks>
    public float EagerRefreshThreshold { get; set; } = 0.9f;

    /// <summary>
    /// Gets or sets the soft timeout duration, in milliseconds, for factory operations.
    /// </summary>
    /// <remarks>This property defines the maximum time allowed for factory operations to complete before
    /// timing out. A value of 100 milliseconds is set by default.</remarks>
    public int FactorySoftTimeoutInMilliseconds { get; set; } = 100;

    /// <summary>
    /// Gets or sets the maximum duration, in milliseconds, that a factory operation is allowed to run before it is
    /// forcibly terminated.
    /// </summary>
    /// <remarks>This property defines a hard timeout limit for factory operations. If an operation exceeds
    /// this duration, it will be stopped to prevent excessive resource usage. The default value is 1500
    /// milliseconds.</remarks>
    public int FactoryHardTimeoutInMilliseconds { get; set; } = 1500;

    /// <summary>
    /// Gets or sets the soft timeout duration, in minutes, for the distributed cache.
    /// </summary>
    /// <remarks>This property determines how long cached items remain valid before they are considered
    /// expired. It is important to set this value according to the application's caching strategy to optimize
    /// performance and resource usage.</remarks>
    public int DistributedCacheSoftTimeoutInMinutes { get; set; } = 10;

    /// <summary>
    /// Gets or sets the hard timeout duration, in minutes, for the distributed cache.
    /// </summary>
    /// <remarks>This property defines the maximum time that cached items are retained before they are
    /// considered expired. Adjusting this value can help manage cache memory usage and performance based on application
    /// needs.</remarks>
    public int DistributedCacheHardTimeoutInMinutes { get; set; } = 20;

    /// <summary>
    /// Gets or sets a value indicating whether background operations for distributed cache are enabled.
    /// </summary>
    /// <remarks>When set to <see langword="true"/>, background operations for distributed cache can be
    /// performed asynchronously, which may improve performance by offloading work from the main execution thread. If
    /// set to <see langword="false"/>, these operations are disabled, which may impact performance in scenarios with
    /// high cache activity.</remarks>
    public bool AllowBackgroundDistributedCacheOperationsEnabled { get; set; } = true;

    /// <summary>
    /// Gets or sets the maximum duration, in minutes, for which jitter can be applied to timing operations.
    /// </summary>
    /// <remarks>This property defines the upper limit for the amount of random delay (jitter) that may be
    /// introduced to scheduled operations. Applying jitter can help distribute load more evenly and prevent resource
    /// contention in distributed systems. The default value is 2 minutes.</remarks>
    public int JitterMaxDurationInMinutes { get; set; } = 2;

    /// <summary>
    /// Gets or sets the connection string used to connect to the Redis cache instance.
    /// </summary>
    /// <remarks>The connection string must be properly formatted to ensure successful communication with the
    /// Redis server. Refer to the Redis documentation for supported connection string formats and options.</remarks>
    public string RedisCacheConnectionString { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the connection string used to connect to the Redis backplane.
    /// </summary>
    /// <remarks>This connection string is essential for configuring the Redis backplane, which facilitates
    /// message distribution across multiple servers in a distributed application. Ensure that the connection string is
    /// correctly formatted to establish a successful connection.</remarks>
    public string RedisBackplaneConnectionString { get; set; } = string.Empty;
}